### PR TITLE
Integrate with new Luxmed portal

### LINKED ISSUE #10: Nie działa z nową stroną Lux Medu
Od pewnego czasu Lux Med ma nowy wygląd wyszukiwarki usług. Wtyczka nie działa na nim.

image

### PR DESCRIPTION
**Pull request by kkdrz**
* Integrated with the new Luxmed portal. I tried to not break the old version, but actually, I don't know if it is still in use.
* Added opinions numbers next to the stars
* Only doctor's names are used in the search for new portal. When I added city and profession it searched much worse.

It may not be ideal, but as far as I tested it - it works.
Fixes #10

image
image

### CODE REVIEW

**Comment by mstachniuk** [comment]
Hi @kkdrz 
Thank you so much for your contribution!
I tested quickly your PR and I have a few remarks: 
- There is a need to migrate to manifest v3: https://developer.chrome.com/blog/mv2-transition/ Without that I will be not able to push a new version to Chrome Store :-(
- Quick migration to Manifest v3 returns an error in Manifest: `Unrecognized manifest key 'run_at'.`.
- The stars don't work anymore, there are some errors in execution, most probably because of the new Manifest version. Errors: `Uncaught TypeError: chrome.extension.getURL is not a function` in `getImage()`.

My changes to manifest:
```
  "action": {
    "default_icon": "icon16.png",
    "default_popup": "popup.html"
  },

  "web_accessible_resources": [{
    "resources": ["star-gold-left-10.png",
    "star-gold-right-10.png",
    "star-gray-left-10.png",
    "star-gray-right-10.png"],
    "matches": ["https://portalpacjenta.luxmed.pl/*",
      "https://pu.tuzdrowie.pl/*"]}]
}
```

Could you improve your PR? I will be happy to merge. In case of question, just reply here, or to my e-mail (in git history).

**Comment by mstachniuk** [comment]
Thank you @kkdrz for sending PR. After minor fixes, I will be able to release a new version with your changes.

**Comment by kkdrz** [comment]
@mstachniuk Sorry for not migrating to manifest v3. I had it in the back of my mind, but somehow I could not find free time. Glad that you improved the code and that everything works. Thanks!

**Comment by mstachniuk** [comment]
Your welcome, happy using!

śr., 27 lip 2022, 19:55 użytkownik Konrad Drozd ***@***.***>
napisał:

**Pull request merged**
